import 'package:almohsen_s_application11/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_s_application11/widgets/app_bar/appbar_subtitle_one.dart';import 'package:carousel_slider/carousel_slider.dart';import 'widgets/label_item_widget.dart';import 'models/label_item_model.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_application11/core/app_export.dart';import 'controller/onboarding_one_controller.dart';class OnboardingOneScreen extends GetWidget<OnboardingOneController> {const OnboardingOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, appBar: _buildAppBar(), body: Container(width: SizeUtils.width, height: SizeUtils.height, padding: EdgeInsets.only(top: 45.v), decoration: BoxDecoration(image: DecorationImage(image: AssetImage(ImageConstant.imgOnboardingOne), fit: BoxFit.cover)), child: Container(height: 718.v, width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h), child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgImage, height: 361.v, width: 283.h, alignment: Alignment.topCenter), _buildLabel()]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 49.v, actions: [AppbarSubtitleOne(text: "lbl_skip".tr, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 13.v), onTap: () {onTapMediumLabelMedium();})]); } 
/// Section Widget
Widget _buildLabel() { return Align(alignment: Alignment.bottomCenter, child: Container(height: 335.v, width: 327.h, margin: EdgeInsets.only(bottom: 5.v), child: Stack(alignment: Alignment.bottomCenter, children: [Obx(() => CarouselSlider.builder(options: CarouselOptions(height: 335.v, initialPage: 0, autoPlay: true, viewportFraction: 1.0, enableInfiniteScroll: false, scrollDirection: Axis.horizontal, onPageChanged: (index, reason) {controller.sliderIndex.value = index;}), itemCount: controller.onboardingOneModelObj.value.labelItemList.value.length, itemBuilder: (context, index, realIndex) {LabelItemModel model = controller.onboardingOneModelObj.value.labelItemList.value[index]; return LabelItemWidget(model);})), Align(alignment: Alignment.bottomCenter, child: Obx(() => Container(height: 10.v, margin: EdgeInsets.only(bottom: 112.v), child: AnimatedSmoothIndicator(activeIndex: controller.sliderIndex.value, count: controller.onboardingOneModelObj.value.labelItemList.value.length, axisDirection: Axis.horizontal, effect: ScrollingDotsEffect(spacing: 12, activeDotColor: theme.colorScheme.primary, dotColor: theme.colorScheme.primary.withOpacity(0.41), dotHeight: 10.v, dotWidth: 10.h)))))]))); } 
/// Navigates to the signUpCreateAcountScreen when the action is triggered.
onTapMediumLabelMedium() { Get.toNamed(AppRoutes.signUpCreateAcountScreen, ); } 
 }
