import 'package:almohsen_s_application11/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_s_application11/widgets/app_bar/appbar_leading_image.dart';import 'package:almohsen_s_application11/widgets/app_bar/appbar_title.dart';import 'package:almohsen_s_application11/widgets/app_bar/appbar_trailing_image.dart';import 'package:almohsen_s_application11/widgets/custom_search_view.dart';import 'widgets/message_item_widget.dart';import 'models/message_item_model.dart';import 'package:almohsen_s_application11/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:almohsen_s_application11/core/app_export.dart';import 'controller/message_controller.dart';import 'models/message_model.dart';
// ignore_for_file: must_be_immutable
class MessagePage extends StatelessWidget {MessagePage({Key? key}) : super(key: key);

MessageController controller = Get.put(MessageController(MessageModel().obs));

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.all(24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.end, children: [SizedBox(height: 4.v), CustomSearchView(controller: controller.searchController, hintText: "lbl_search_message".tr), SizedBox(height: 24.v), _buildDot(), SizedBox(height: 16.v), Divider(), SizedBox(height: 15.v), _buildAvatar(), SizedBox(height: 16.v), Divider(), SizedBox(height: 15.v), _buildMessage(), Spacer(), CustomElevatedButton(height: 46.v, width: 137.h, text: "lbl_new_chat".tr, leftIcon: Container(margin: EdgeInsets.only(right: 4.h), child: CustomImageView(imagePath: ImageConstant.imgPlusOnprimarycontainer, height: 18.adaptSize, width: 18.adaptSize)), buttonStyle: CustomButtonStyles.fillPrimaryTL20, buttonTextStyle: CustomTextStyles.titleSmallOnPrimaryContainerSemiBold)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 51.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgComponent1, margin: EdgeInsets.only(left: 24.h, top: 13.v, bottom: 14.v), onTap: () {onTapImage();}), centerTitle: true, title: AppbarTitle(text: "lbl_message".tr), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgComponent3, margin: EdgeInsets.fromLTRB(16.h, 13.v, 16.h, 14.v))]); } 
/// Section Widget
Widget _buildDot() { return GestureDetector(onTap: () {onTapDot();}, child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 56.adaptSize, width: 56.adaptSize, child: Stack(alignment: Alignment.bottomRight, children: [CustomImageView(imagePath: ImageConstant.imgImage56x56, height: 56.adaptSize, width: 56.adaptSize, radius: BorderRadius.circular(28.h), alignment: Alignment.center), Align(alignment: Alignment.bottomRight, child: Container(height: 16.adaptSize, width: 16.adaptSize, decoration: BoxDecoration(color: appTheme.green600, borderRadius: BorderRadius.circular(8.h), border: Border.all(color: theme.colorScheme.onPrimaryContainer.withOpacity(1), width: 1.h))))])), Padding(padding: EdgeInsets.only(left: 12.h, top: 3.v), child: _buildNameDescription(dynamicText1: "lbl_esther_howard".tr, dynamicText2: "msg_lorem_ipsum_dolor4".tr)), Spacer(), Padding(padding: EdgeInsets.only(top: 7.v), child: _buildTime(timeText: "lbl_10_20".tr, widgetText: "lbl_2".tr))])); } 
/// Section Widget
Widget _buildAvatar() { return GestureDetector(onTap: () {onTapAvatar();}, child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgAvatar, height: 56.adaptSize, width: 56.adaptSize, radius: BorderRadius.circular(28.h)), Padding(padding: EdgeInsets.only(left: 12.h, top: 3.v), child: _buildNameDescription(dynamicText1: "lbl_wade_warren".tr, dynamicText2: "msg_lorem_ipsum_dolor4".tr)), Spacer(), Padding(padding: EdgeInsets.only(top: 7.v), child: _buildTime(timeText: "lbl_10_20".tr, widgetText: "lbl_2".tr))])); } 
/// Section Widget
Widget _buildMessage() { return Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return Padding(padding: EdgeInsets.symmetric(vertical: 7.5.v), child: SizedBox(width: 327.h, child: Divider(height: 1.v, thickness: 1.v, color: appTheme.gray300)));}, itemCount: controller.messageModelObj.value.messageItemList.value.length, itemBuilder: (context, index) {MessageItemModel model = controller.messageModelObj.value.messageItemList.value[index]; return MessageItemWidget(model);})); } 
/// Common widget
Widget _buildNameDescription({required String dynamicText1, required String dynamicText2, }) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(dynamicText1, style: CustomTextStyles.titleMediumBold.copyWith(color: theme.colorScheme.primary)), SizedBox(height: 9.v), Text(dynamicText2, style: CustomTextStyles.titleSmallBluegray400.copyWith(color: appTheme.blueGray400))]); } 
/// Common widget
Widget _buildTime({required String timeText, required String widgetText, }) { return Column(children: [Text(timeText, style: CustomTextStyles.labelLargeSemiBold.copyWith(color: appTheme.blueGray400)), SizedBox(height: 6.v), Align(alignment: Alignment.centerRight, child: Container(width: 24.adaptSize, padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 5.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.circleBorder12), child: Text(widgetText, style: theme.textTheme.labelMedium!.copyWith(color: theme.colorScheme.onPrimaryContainer.withOpacity(1)))))]); } 

/// Navigates to the previous screen.
onTapImage() { Get.back(); } 
/// Navigates to the chatScreen when the action is triggered.
onTapDot() { Get.toNamed(AppRoutes.chatScreen, ); } 
/// Navigates to the chatScreen when the action is triggered.
onTapAvatar() { Get.toNamed(AppRoutes.chatScreen, ); } 
 }
